server:
  port: 8083

spring:
  application:
    name: techfood-pedidos

    cloud:
      config:
        enabled: false

  profiles:
    active: dev

  datasource:
#    url: jdbc:postgresql://localhost:5435/techfood-pedidos
    url: jdbc:postgresql://postgres:5435/techfood-pedidos
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

#client:
#  service:
#    base-url: http://localhost:8081
#
#product:
#  service:
#    base-url: http://localhost:8082
client:
  service:
    base-url: http://techfood-clientes:8081
product:
  service:
    base-url: http://techfood-produtos:8082
